export const GRADOVI_SRBIJE: string[] = [
  'Beograd',
  'Bor',
  'Valjevo',
  'Vranje',
  'Vršac',
  'Zaječar',
  'Zrenjanin',
  'Jagodina',
  'Kikinda',
  'Kragujevac',
  'Kraljevo',
  'Kruševac',
  'Leskovac',
  'Loznica',
  'Niš',
  'Novi Pazar',
  'Novi Sad',
  'Pančevo',
  'Pirot',
  'Požarevac',
  'Priština',
  'Prokuplje',
  'Smederevo',
  'Sombor',
  'Sremska Mitrovica',
  'Subotica',
  'Užice',
  'Čačak',
  'Šabac',
].sort((a, b) => a.localeCompare(b, 'sr'));
